### ISSUE TITLE
Eski harddiskten yeni pc'ye atılan AnyOtp'nin eski şifreyi kabul etmeme sorunu

### ISSUE THREAD

**Issue by dsipahioglu** [mmtylcn27/AnyOTPMover#1]
Eski bilgisayarımın bios çökmüştü. Hard diskini başka bilgisayara usb ile bağlayarak CopyOtp.exe'yi çalıştırdım, oradan da çöken bilgisayarımı seçtim. İki tane dosya çıktı, reg ve spoof dosyaları, onları başka bir usb'ye attım.

OTP kurmak istediğim Yeni cihazdan AnyOtp sayfasına girip setup indirdim, o setupı çalıştırdım.

Program files altından Otp'nin kurulduğu klasöre gittim ve dosyaları attığım usb'den spoof infoyu o klasördeki AnyOtp.exe'nin yanına attım. Reg dosyasını çalıştırdım, sonra da AnyOtp.exe'yi ilk defa orada çalıştırdım.

Auth sayfası değil de, doğru bir şekilde Şifre sorma sayfası geldi, ancak girdiğim şifrem doğru olmasına rağmen yanlış şifre giriyorsunuz hatası verdi. 2 hakkım kaldı. Neyi yanlış yapıyorum acaba, eksik mi çekiyor bilgileri :/

**Comment by mmtylcn27** [comment]
StartOTP.exe ile Otp'yi açmanız gerekiyor normal olarak açarsanız çalışmaz
