### ISSUE TITLE
İşlemci Değişikliği Otp Taşıma

### ISSUE THREAD

**Issue by bberkant** [mmtylcn27/AnyOTPMover#2]
Merhaba ben işlemcimi yükselttim otplerim gitti şifre yanlış diyor eski işlemciyi takip mover'ı kullansam sonra yeni işlemciyi takıp yapsam olur mu acaba

**Comment by mmtylcn27** [comment]
Uzun bir süredir AnyOtp ile ilgili bir çalışma yapmıyorum. Bu konuda tam bir fikrim yok en son hatırladığım kadarıyla sadece disk ile ilgili bir durum vardı.
